# Generated by Django 3.1.1 on 2020-09-29 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200929_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='tag',
            new_name='tags',
        ),
    ]
