# Generated by Django 3.1.1 on 2020-10-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200929_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('интернет-маркетинг', 'интернет-маркетинг'), ('веб-разработка', 'веб-разработка')], max_length=255)),
            ],
        ),
    ]
